### ISSUE TITLE
Can not generate sharp-looking Terminus TTF

### ISSUE THREAD

**Issue by luzh** [Tblue/mkttf#3]
Hi,

Thanks for creating Terminus TTF and making the scripts available! I tried to generate a patched version of Terminus (td1, with centered tidle ~), but I failed to generate the same sharp-looking fonts as you provided on files.ax86.net. See the attached figure (left - my generated version, right - your version). The difference is quite obvious for font sizes 12 - 24.

![ttf](https://user-images.githubusercontent.com/1196285/41019785-1568ef70-6915-11e8-989c-dcdf2a9f6d8a.png)

I've followed steps as you mentioned in the README file. Do you have any idea why this difference happens and are there any parameters I need to tune to generate the same sharp-looking TTF fonts?

**Comment by Tblue** [comment]
Hey,

sorry for the very late reply! Things have been busy...

You likely need to add the `--visual-studio-fixes` (or just `-s`) option to your invocation of `mkttf.sh` (which `dist.sh` already does when generating the Windows variant of Terminus TTF). I will edit the README to include that information.

That option enables Windows-specific fixes without which Windows does not use the bitmaps embedded in the font, at the loss of certain Hiragana characters; the full details are here: http://www.electronicdissonance.com/2010/01/raster-fonts-in-visual-studio-2010.html

I generated a TTF version of the `td1` variant for you. Please find it here: https://files.ax86.net/terminus-ttf/files/4.47.0/variants/

**Comment by luzh** [comment]
Thanks for your kind assistance!
