### ISSUE TITLE
Segmentation fault (core dumped) mkttf.py *.bdf

### ISSUE THREAD

**Issue by oxr463** [Tblue/mkttf#7]
```sh
./mkttf.py *.bdf
/bin/bash: line 101:  1462 Segmentation fault      (core dumped) ./mkttf.py *.bdf
```

**Comment by Tblue** [comment]
Please provide more details:

- Which FontForge version are you using?
- Which Linux distribution are you using?
- What's the output of `python --version`?

**Comment by Tblue** [comment]
Please also enable core dumps using `ulimit -c unlimited`, run the `mkttf.py` script again, and provide the core dump file `core` from the current working directory.

If no `core` dump file exists, please try obtaining the core dump using [`coredumpctl`](https://www.freedesktop.org/software/systemd/man/coredumpctl.html#).

**Comment by oxr463** [comment]
> * Which FontForge version are you using?

- https://packages.debian.org/buster/python-fontforge

> * Which Linux distribution are you using?

- Debian Buster
 
> * What's the output of `python --version`?

- `Python 3.7.3`

**Comment by oxr463** [comment]
> 
> 
> Please also enable core dumps using `ulimit -c unlimited`, run the `mkttf.py` script again, and provide the core dump file `core` from the current working directory.
> 
> If no `core` dump file exists, please try obtaining the core dump using [`coredumpctl`](https://www.freedesktop.org/software/systemd/man/coredumpctl.html#).

This is running in GitLab CI/CD shared runner, so unfortunately I am not able to create a core dump.

Here is the pipeline log: https://gitlab.com/oxr463/tsf/-/jobs/459792485

Here is the source: https://gitlab.com/oxr463/tsf/-/blob/mkttf/.gitlab-ci.yml

**Comment by Tblue** [comment]
Sorry for losing sight of this bug... Can you still reproduce this? I've used `mkttf` just now and had no segfaults.

**Comment by oxr463** [comment]
> Sorry for losing sight of this bug... Can you still reproduce this? I've used `mkttf` just now and had no segfaults.

We can close this.
