### ISSUE TITLE
Conversion problem

### ISSUE THREAD

**Issue by larsbrinkhoff** [Tblue/mkttf#9]
Hello,

I tried to convert this BDF file: https://github.com/larsbrinkhoff/xgp-fonts/blob/master/bdf/40vshd.bdf

According to https://products.aspose.app/font/viewer, I get this.  Why the wide spacing?
![40vshd](https://user-images.githubusercontent.com/775050/132677526-853c15bc-f6bd-400f-bb6c-be3860c47ced.png)

**Comment by Tblue** [comment]
Sorry for not looking into this earlier.

I have made a change to `mkttf` that should drastically improve outline quality, can you please retry with the latest version?

**Comment by Tblue** [comment]
Looks like this is an issue with the BDF file and not `mkttf`: The `SWIDTH` (scalable width) in the file is set to such a large value that the font looks like that.

I used [FontForge's Auto Width dialog](https://fontforge.org/docs/ui/dialogs/autowidth.html) to adjust the width, and now things look better:

![40VSHDKSTMedium](https://user-images.githubusercontent.com/842305/230986622-ea68b607-7634-4416-af6f-178b6b76148f.png)

I'm attaching the TTF and SFD files for your convenience: [40vshd.zip](https://github.com/Tblue/mkttf/files/11193563/40vshd.zip)

Feel free to re-open this issue if necessary.
